module FcsCppPlace

  @@fcs_libs = {
    'fcs_utils_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/utils/src',
    'fcs_utils_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/utils',
    'fcs_utils_exception_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/utils/exception/src',
    'fcs_utils_exception_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/utils/exception',
    'fcs_utils_synch_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/utils/synch/src',
    'fcs_utils_synch_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/utils/synch',
    'fcs_utils_performance_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/utils/performance/src',
    'fcs_utils_performance_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/utils/performance',
    'fcs_utils_streamers_table_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/utils/streamers/table/src',
    'fcs_utils_streamers_table_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/utils/streamers/table',
    'fcs_utils_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/utils/src',
    'fcs_utils_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/utils',
    'fcs_patterns_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/patterns/src',
    'fcs_patterns_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/patterns',
    'fcs_dev_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/dev/src',
    'fcs_dev_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/dev',
    'fcs_codegen_coverage_richdata_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/codegen/coverage/src',
    'fcs_codegen_coverage_richdata_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/codegen/coverage',
    'fcs_table_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/table/src',
    'fcs_table_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/table',
    'fcs_h5_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/h5/src',
    'fcs_h5_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/h5',
    'fcs_h5_utils_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/h5/utils/src',
    'fcs_h5_utils_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/h5/utils',
    'fcs_h5_table_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/h5_table/src',
    'fcs_h5_table_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/h5_table',
    'fcs_gui_environment_selection_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/gui/environment/src',
    'fcs_gui_environment_selection_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/gui/environment',
    'fcs_gui_selection_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/gui/selection/src',
    'fcs_gui_selection_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/gui/selection',
    'fcs_gui_search_selection_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/gui/search/src',
    'fcs_gui_search_selection_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/gui/search',
    'fcs_gui_table_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/gui/table/src',
    'fcs_gui_table_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/gui/table',
    'fcs_orm_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/orm/src',
    'fcs_orm_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/orm',
    'fcs_orm_test_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/orm/test/src',
    'fcs_orm_test_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/orm/test',
    'fcs_table_test_table_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/table/test/src',
    'fcs_table_test_table_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/table/test',
    'fcs_environment_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/environment/src',
    'fcs_environment_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/environment',
    'fcs_app_sig_handler_application_signal_handler_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/app_sig_handler/src',
    'fcs_app_sig_handler_application_signal_handler_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/app_sig_handler',
    'fcs_linux_specific_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/linux_specific/src',
    'fcs_linux_specific_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/linux_specific',
    'fcs_raii_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/raii/src',
    'fcs_raii_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/raii',
    'fcs_timestamp_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/timestamp/src',
    'fcs_timestamp_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/timestamp',
    'fcs_mongoid_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/mongoid/src',
    'fcs_mongoid_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/mongoid',
    'fcs_orm_system_table_system_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/orm/system/table/src',
    'fcs_orm_system_table_system_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/orm/system/table',
    'fcs_orm_system_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/orm/system/src',
    'fcs_orm_system_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/orm/system',
    'fcs_orm_code_metrics_table_code_metrics_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/orm/code_metrics/table/src',
    'fcs_orm_code_metrics_table_code_metrics_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/orm/code_metrics/table',
    'fcs_orm_code_metrics_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/orm/code_metrics/src',
    'fcs_orm_code_metrics_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/orm/code_metrics',
    'fcs_orm_code_metrics_query_cpp'=> '/home/dbdavidson/open_source/codegen/cpp/libs/fcs/orm/code_metrics/query/src',
    'fcs_orm_code_metrics_query_include'=> '/home/dbdavidson/open_source/codegen/cpp/fcs/orm/code_metrics/query',
  }

  def fcs_libs() 
    return @@fcs_libs
  end

end
