name: ebisu_dlang
version: 0.0.1
description: >
  A library that supports code generation of dart and others
dependencies:
  pathos:
  ebisu:
      path: ../ebisu
# custom <ebisu_dlang dependencies>
# end <ebisu_dlang dependencies>

