require 'examples/cpp/app_sample'
require 'examples/cpp/lib_examples_camel_case_filename'
require 'examples/cpp/lib_examples_nested'
require 'examples/cpp/lib_sample_different_named_header'
require 'examples/cpp/lib_sample'
require 'examples/cpp/lib_class_group'
require 'examples/cpp/all_mongoids'
